Nombre = "Lolo"
print("Nombre = " + Nombre)
Apellidos = "del Castillo"
print("Apellidos = " + Apellidos)
Edad = "22"
print("Edad = " + Edad)
Email = "lolito_Aridama@gmail.com"
print("Email = " + Email)
Teléfono = "655631455"
print("Teléfono = " + Teléfono)
Casado = False
print("Casado = " , Casado)
Hijos = False 
print("Hijos = " , Hijos)
Lista_de_amigos = ["Anabel", "Ricardo", "Teresa", "Bea"]
print("Amigos = " , Lista_de_amigos)
Películas_vistas = {"Peli1" : "Ghost", "Peli2" : "Up", "Peli3": "La vida es bella" }
print("Pelis = " , Películas_vistas)
